### ISSUE TITLE
Random crash in WallpapersFragment

### ISSUE THREAD

**Issue by jahirfiquitiva** [jahirfiquitiva/IconShowcase#109]
```java
com.afollestad.materialdialogs.MaterialDialog$DialogException: Bad window token, you cannot show a dialog before an Activity is created or after it's hidden.
	at com.afollestad.materialdialogs.MaterialDialog.show(Unknown Source)
	at com.afollestad.materialdialogs.MaterialDialog$Builder.show(Unknown Source)
	at jahirfiquitiva.iconshowcase.fragments.WallpapersFragment.showApplyWallpaperDialog(Unknown Source)
	at jahirfiquitiva.iconshowcase.fragments.WallpapersFragment.access$000(Unknown Source)
	at jahirfiquitiva.iconshowcase.fragments.WallpapersFragment$1$1.onClick(Unknown Source)
	at jahirfiquitiva.iconshowcase.adapters.WallpapersAdapter$WallsHolder.onClick(Unknown Source)
	at android.view.View.performClick(View.java:5254)
	at android.view.View$PerformClick.run(View.java:21203)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6881)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by AllanWang** [comment]
I think we my as well rework all the dialogs. You used to hold on to the object, which you shouldn't need to do. Check how ChangelogDialog was done compared to the old ISDialogs

**Comment by jahirfiquitiva** [comment]
Steps to reproduce:
enter settings, go to section "display" go to background/wallpaper, choose not gallery or others but the icon dashboard app, the app opens it wallpaper tab, wallpaper is tapped, icon dashboard silent FC

[More info](https://github.com/jahirfiquitiva/IconShowcase-Dashboard/issues/6)

**Comment by jahirfiquitiva** [comment]
I think crash doesn't happen anymore, but the section doesn't load...

![screenshot_20160911-170025](https://cloud.githubusercontent.com/assets/10360816/18420891/1df20c04-7843-11e6-8d0b-967488abf2c7.png)

**Comment by AllanWang** [comment]
[Fixed](https://github.com/jahirfiquitiva/IconShowcase/commit/67821e3dd3e129b4501a0e1ef666c4d012acd4ef)
