### ISSUE TITLE
App crashes when trying to show 'License check' dialog

### ISSUE THREAD

**Issue by jahirfiquitiva** [jahirfiquitiva/IconShowcase#139]
```
E/WindowManager: android.view.WindowLeaked: Activity jahirfiquitiva.iconshowcase.activities.ShowcaseActivity has leaked window DecorView@c5f0fe2[] that was originally added here
   at android.view.ViewRootImpl.<init>(ViewRootImpl.java:417)
   at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
   at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
   at android.app.Dialog.show(Dialog.java:316)
   at com.afollestad.materialdialogs.MaterialDialog.show(Unknown Source)
   at jahirfiquitiva.iconshowcase.dialogs.ISDialogs.showLicenseFailDialog(Unknown Source)
   at jahirfiquitiva.iconshowcase.activities.ShowcaseActivity.showNotLicensedDialog(Unknown Source)
   at jahirfiquitiva.iconshowcase.activities.ShowcaseActivity.access$1200(Unknown Source)
   at jahirfiquitiva.iconshowcase.activities.ShowcaseActivity$4.dontAllow(Unknown Source)
   at com.github.javiersantos.piracychecker.PiracyChecker.verify(Unknown Source)
   at com.github.javiersantos.piracychecker.PiracyChecker.start(Unknown Source)
   at jahirfiquitiva.iconshowcase.activities.ShowcaseActivity.checkLicense(Unknown Source)
   at jahirfiquitiva.iconshowcase.activities.ShowcaseActivity.runLicenseChecker(Unknown Source)
   at jahirfiquitiva.iconshowcase.activities.ShowcaseActivity.onCreate(Unknown Source)
   at android.app.Activity.performCreate(Activity.java:6664)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2614)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2722)
   at android.app.ActivityThread.-wrap12(ActivityThread.java)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1471)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:154)
   at android.app.ActivityThread.main(ActivityThread.java:6127)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

**Comment by AllanWang** [comment]
This will be fixed once all the dialogs are redone

**Comment by jahirfiquitiva** [comment]
Thanks @AllanWang :)
