### ISSUE TITLE
Fix Permissions request logic

### ISSUE THREAD

**Issue by jahirfiquitiva** [jahirfiquitiva/IconShowcase#14]
Desired behavior:

```java
if (!permissionGranted) {   
    if (permissionsCantBeAskedAnymore) {
        showErrorDialog();
    } else {
        requestPermissions(OnPermissionsResult{
            if (permissionGranted) {
                taskWithNeedOfPermissions();
			} else {
				showErrorDialog();
			}
        });
    }   
} else {    
    taskWithNeedOfPermissions();    
}

private void taskWithNeedOfPermissions(){
    // Run, do, or execute something.
}
```

I hope someone help me achieve it.

**Comment by jahirfiquitiva** [comment]
@PDDStudio @AkshayChordiya ... any chance you could give a look at this again?

**Comment by jahirfiquitiva** [comment]
**Update**

To be added/fixed just in:

https://github.com/jahirfiquitiva/IconShowcase/blob/master/showcase/src/main/java/jahirfiquitiva/iconshowcase/fragments/SettingsFragment.java#L195

**Comment by PDDStudio** [comment]
Still open?

**Comment by AllanWang** [comment]
@PDDStudio don't think so. I thought this was fixed a while back already.

**Comment by jahirfiquitiva** [comment]
@PDDStudio
Is almost fixed.
Only thing needed is to make the dialog to change wallpapers download folder, right after allowing permission.

https://github.com/jahirfiquitiva/IconShowcase/blob/master/library/src/main/java/jahirfiquitiva/iconshowcase/fragments/SettingsFragment.java#L293

**Comment by jahirfiquitiva** [comment]
@PDDStudio 

Is almost fixed.
Only thing needed is to make the dialog, to change wallpapers download folder, appear, right after allowing permission.

https://github.com/jahirfiquitiva/IconShowcase/blob/master/library/src/main/java/jahirfiquitiva/iconshowcase/fragments/SettingsFragment.java#L213

Currently, if I try to make it show, uncommenting [this line](https://github.com/jahirfiquitiva/IconShowcase/blob/master/library/src/main/java/jahirfiquitiva/iconshowcase/fragments/SettingsFragment.java#L556), an error occurs, here's the log:
```
E/AndroidRuntime: FATAL EXCEPTION: main
   Process: jahirfiquitiva.apps.iconshowcase.sampleip, PID: 13801
   Theme: themes:{default=overlay:jahirfiquitiva.themes.meliornui.prime, iconPack:com.kmzdsgns.kmz, com.android.systemui=overlay:jahirfiquitiva.themes.meliornui.prime, com.android.systemui.navbar=overlay:jahirfiquitiva.themes.meliornui.prime}
   java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=42, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {jahirfiquitiva.apps.iconshowcase.sampleip/jahirfiquitiva.iconshowcase.activities.ShowcaseActivity}: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	   at android.app.ActivityThread.deliverResults(ActivityThread.java:3745)
	   at android.app.ActivityThread.handleSendResult(ActivityThread.java:3788)
	   at android.app.ActivityThread.-wrap16(ActivityThread.java)
	   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412)
	   at android.os.Handler.dispatchMessage(Handler.java:102)
	   at android.os.Looper.loop(Looper.java:148)
	   at android.app.ActivityThread.main(ActivityThread.java:5475)
	   at java.lang.reflect.Method.invoke(Native Method)
	   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
	   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
	Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	   at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1527)
	   at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1545)
	   at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:654)
	   at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:621)
	   at android.support.v4.app.DialogFragment.show(DialogFragment.java:139)
	   at jahirfiquitiva.iconshowcase.dialogs.FolderChooserDialog.show(Unknown Source)
	   at jahirfiquitiva.iconshowcase.fragments.SettingsFragment.showFolderChooserDialog(Unknown Source)
	   at jahirfiquitiva.iconshowcase.fragments.SettingsFragment.onStoragePermissionGranted(Unknown Source)
	   at jahirfiquitiva.iconshowcase.activities.ShowcaseActivity.onRequestPermissionsResult(Unknown Source)
	   at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7456)
	   at android.app.Activity.dispatchActivityResult(Activity.java:7334)
	   at android.app.ActivityThread.deliverResults(ActivityThread.java:3741)
	   at android.app.ActivityThread.handleSendResult(ActivityThread.java:3788) 
	   at android.app.ActivityThread.-wrap16(ActivityThread.java) 
	   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412) 
	   at android.os.Handler.dispatchMessage(Handler.java:102) 
	   at android.os.Looper.loop(Looper.java:148) 
	   at android.app.ActivityThread.main(ActivityThread.java:5475) 
	   at java.lang.reflect.Method.invoke(Native Method) 
	   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
	   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
	   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102) 
```

**Comment by AllanWang** [comment]
Try commenting out this line

https://github.com/jahirfiquitiva/IconShowcase/blob/master/library/src/main/java/jahirfiquitiva/iconshowcase/activities/ShowcaseActivity.java#L478

I just googled it and apparently it's a support package error.

**Comment by PDDStudio** [comment]
@AllanWang are you going to fix this or shall I ?

**Comment by jahirfiquitiva** [comment]
@AllanWang I'm not sure about commenting that line, because it's used to restore the state of the app after resuming it, isn't it?

@PDDStudio if you have another way to do it, or if it's really ok to comment or remove that line, feel free to change what's needed.

Whoever does it first, help is welcome and highly appreciated.

**Comment by AllanWang** [comment]
@PDDStudio feel free to fix it. I just offered a suggestion based on what I quickly googled. Didn't really look into it.

**Comment by PDDStudio** [comment]
Done. Closing this

**Comment by jahirfiquitiva** [comment]
Thank you so much Patrick
