### ISSUE TITLE
Home Section Window Leak

### ISSUE THREAD

**Issue by asdfasdfvful** [jahirfiquitiva/IconShowcase#77]
Opening the app when there is a new version does not pop up the changelog. There is the following error:

```
03-04 15:38:38.023 22843-22843/jahirfiquitiva.apps.iconshowcase.sample E/WindowManager: android.view.WindowLeaked: Activity jahirfiquitiva.apps.iconshowcase.sample.HomeActivity has leaked window com.android.internal.policy.PhoneWindow$DecorView{7dabda6 V.E...... R.....ID 0,0-1025,878} that was originally added here
	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:368)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:299)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
	at android.app.Dialog.show(Dialog.java:319)
	at com.afollestad.materialdialogs.MaterialDialog.show(MaterialDialog.java:1350)
	at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:1341)
	at jahirfiquitiva.iconshowcase.dialogs.ISDialogs.showChangelogDialog(ISDialogs.java:84)
	at jahirfiquitiva.iconshowcase.activities.ShowcaseActivity.showChangelogDialog(ShowcaseActivity.java:635)
	at jahirfiquitiva.iconshowcase.activities.ShowcaseActivity.runLicenseChecker(ShowcaseActivity.java:603)
	at jahirfiquitiva.iconshowcase.activities.ShowcaseActivity.onCreate(ShowcaseActivity.java:261)
	at jahirfiquitiva.apps.iconshowcase.sample.HomeActivity.onCreate(HomeActivity.java:35)
	at android.app.Activity.performCreate(Activity.java:6251)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
```

**Comment by asdfasdfvful** [comment]
Fix for leak (though dialog still isn't popping up on new version change)

ShowcaseActivity: 

`    public static MaterialDialog settingsDialog, loadIcons, **changelog**;
`

`@Override
    protected void onDestroy() {
        super.onDestroy();
        if (settingsDialog != null) {
            settingsDialog.dismiss();
            settingsDialog = null;
        }
       ** if (changelog != null) {
            changelog.dismiss();
            changelog = null;
        }**
    }

`


IS Dialog:

`public static void showChangelogDialog(Context context) {
        if (context.getResources().getBoolean(R.bool.changelog_ripples)) {
           ** ShowcaseActivity.changelog = **new MaterialDialog.Builder(context)
                    .title(R.string.changelog_dialog_title)
                    .adapter(new ChangelogAdapter(context, R.array.fullchangelog), null)
                    .positiveText(R.string.great)
                 **   .build();
            ShowcaseActivity.changelog.show();**
        } else {
            ** ShowcaseActivity.changelog = **new MaterialDialog.Builder(context)
                    .title(R.string.changelog_dialog_title)
                    .adapter(new ChangelogAdapter(context, R.array.fullchangelog), null)
                    .positiveText(R.string.great)
                    .listSelector(android.R.color.transparent)
                  **  .build();
            ShowcaseActivity.changelog.show();**
        }
    }`
